<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>hypergraph_neural_network</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <DefaultItemExcludes>$(DefaultItemExcludes);hypergraph-unit-tests/**</DefaultItemExcludes>
  </PropertyGroup>

</Project>
