// ---------------------------------------------------------------------------
// Package: main
// File:    main.go
//
// Description:
//
//	This program demonstrates the practical application of Contraction
//	Hierarchies (CH) for road network routing. It initializes a graph
//	representing a simple city layout, performs node contraction to
//	generate shortcuts, and displays the resulting augmented graph.
//
// Usage:
//
//	Run the program to see how the graph evolves from a standard road
//	network into a hierarchy of shortcuts designed for fast traversal.
//
// -----------------------------------------------------------------------------
package main

import (
	"fmt"
	"log"

	"github.com/bgolesoftwaredeveloper/contraction-hierachies/contractionhierachies"
)

func main() {
	// 1. Initialize a new Graph structure.
	// We'll use 4 nodes:
	// 0: Residential Sector
	// 1: Local Intersection (The node to be contracted)
	// 2: Downtown Hub
	// 3: Industrial Park
	count := 4
	roadNetwork, err := contractionhierachies.NewGraph(count)

	if err != nil {
		log.Fatalf("Critical error initializing graph: %v", err)
	}

	// 2. Populate the graph with initial directed edges (Standard Roads).
	// Path A: Residential (0) -> Local Intersection (1) [Weight: 10]
	// Path B: Local Intersection (1) -> Downtown Hub (2) [Weight: 15]
	// Path C: Residential (0) -> Industrial Park (3)    [Weight: 40]
	roadNetwork.AddDirectedEdge(0, 1, 10.0)
	roadNetwork.AddDirectedEdge(1, 2, 15.0)
	roadNetwork.AddDirectedEdge(0, 3, 40.0)

	fmt.Println("=== Initial Map State ===")

	fmt.Print(roadNetwork.String())

	// 3. Perform Node Contraction.
	// We "contract" Node 1. This simulates the preprocessing step where
	// minor intersections are simplified into direct shortcuts between
	// more important nodes.
	fmt.Printf("\n--- Preprocessing: Contracting Node 1 ---\n")

	shortcuts, err := roadNetwork.Contract(1)

	if err != nil {
		log.Printf("Warning during contraction: %v", err)
	}

	// 4. Review the Shortcuts generated by the engine.
	// Since 0 -> 1 and 1 -> 2 existed, a shortcut 0 -> 2 (Weight 25)
	// should be created to bypass Node 1.
	if len(shortcuts) > 0 {
		fmt.Printf("Engine generated %d new shortcuts.\n", len(shortcuts))

		for _, edge := range shortcuts {
			fmt.Printf("Created Shortcut: %d -> %d | Total Cost: %.2f\n",
				edge.Source, edge.Destination, edge.Weight)
		}
	}

	// 5. Final Output.
	// The String() method uses internal logic to display both standard
	// roads and shortcuts while maintaining encapsulation.
	fmt.Println("\n=== Final Augmented Hierarchy ===")

	fmt.Print(roadNetwork.String())

	// Encapsulation Check: Note that we cannot access roadNetwork.forwardEdges
	// directly here; we must use public methods like RetrieveEdges.
	nodeZeroEdges, _ := roadNetwork.RetrieveEdges(0)

	fmt.Printf("\nNode 0 (Residential) now has %d outbound route options.\n", len(nodeZeroEdges))
}
