// -----------------------------------------------------------------------------
// Package: golombcodedset
// File: arithmetic.go
//
// Description:
//
//	This file contains low-level arithmetic utilities used by the
//	Golomb-Coded Set implementation, including 128-bit multiplication
//	and fast range reduction without modulo bias.
//
// -----------------------------------------------------------------------------
package golombcodedset

// multiplyUint64 multiplies two 64-bit unsigned integers and returns the full
// 128-bit product as two 64-bit values.
// The returned values represent the high and low halves of the product,
// respectively. This function is used to implement fast range reduction
// without relying on platform-specific 128-bit integer support.
func multiplyUint64(multiplicand, multiplier uint64) (uint64, uint64) {
	const lowerMask = uint64(0xFFFFFFFF)

	// Split each 64-bit operand into 32-bit halves.
	multiplicandLow := multiplicand & lowerMask
	multiplicandHigh := multiplicand >> 32
	multiplierLow := multiplier & lowerMask
	multiplierHigh := multiplier >> 32

	// Compute all partial products from long multiplication.
	partialProductLowLow := multiplicandLow * multiplierLow
	crossProductLowHigh := multiplicandLow * multiplierHigh
	crossProductHighLow := multiplicandHigh * multiplierLow
	partialProductHighHigh := multiplicandHigh * multiplierHigh

	// Accumulate the carry generated by the lower 64-bit region.
	carry := (partialProductLowLow >> 32) +
		(crossProductLowHigh & lowerMask) +
		(crossProductHighLow & lowerMask)

	// Assemble the lower 64 bits of the 128-bit product.
	lower64Bits := (partialProductLowLow & lowerMask) | (carry << 32)

	// Assemble the upper 64 bits of the 128-bit product.
	upper64Bits := partialProductHighHigh +
		(crossProductLowHigh >> 32) +
		(crossProductHighLow >> 32) +
		(carry >> 32)

	return upper64Bits, lower64Bits
}

// fastRangeReduction maps a uniformly distributed 64-bit value into the range
// [0, rangeLimit) using multiplication-based reduction.
// The method avoids modulo bias and relies on the high 64 bits of the
// 128-bit product value * rangeLimit. A zero rangeLimit yields zero.
func fastRangeReduction(value uint64, rangeLimit uint64) uint64 {
	// A zero range produces a degenerate mapping and is treated
	// defensively by returning zero.
	if rangeLimit == 0 {
		return 0
	}

	// Multiply the input value by the range limit and return the
	// high 64 bits of the 128-bit product. This maps uniformly
	// distributed values into [0, rangeLimit) without modulo bias.
	upper64Bits, _ := multiplyUint64(value, rangeLimit)

	return upper64Bits
}
